name: course_compass
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  cloud_firestore: ^4.13.3
  cloud_functions: ^4.5.6
  dynamic_color: ^1.6.8
  file_picker: ^6.1.1
  firebase_auth: ^4.15.0
  firebase_core: ^2.24.0
  firebase_messaging: ^14.7.6
  firebase_storage: ^11.5.3
  firebase_ui_auth: ^1.10.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  google_sign_in: ^6.1.6
  intl: ^0.18.1
  material_symbols_icons: ^4.2711.0
  open_file: ^3.3.2
  path_provider: ^2.1.1
  rxdart: ^0.27.7
  syncfusion_flutter_pdf: ^23.2.6
  table_calendar: ^3.0.9
  weekday_selector: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf
 