// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq1EL-w2lujfSo-HMs0RuOsLrV8DUwmu8',
    appId: '1:725054805811:web:de7dba3d9129302278d046',
    messagingSenderId: '725054805811',
    projectId: 'course-compass',
    authDomain: 'course-compass.firebaseapp.com',
    storageBucket: 'course-compass.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEdJJf85UQA0xO-9hGHEdesatpWIyY-j0',
    appId: '1:725054805811:android:472340513b9d1a4e78d046',
    messagingSenderId: '725054805811',
    projectId: 'course-compass',
    storageBucket: 'course-compass.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGEoSOAu9lBADrfL8M63kd5mhFfgIgHyY',
    appId: '1:725054805811:ios:27d2630386b7cd0178d046',
    messagingSenderId: '725054805811',
    projectId: 'course-compass',
    storageBucket: 'course-compass.appspot.com',
    iosClientId:
        '725054805811-3kk54uhhmj2bkrvuiunm4ltrmteg75bt.apps.googleusercontent.com',
    iosBundleId: 'com.example.courseCompass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGEoSOAu9lBADrfL8M63kd5mhFfgIgHyY',
    appId: '1:725054805811:ios:21a9d9de0ff1a0bf78d046',
    messagingSenderId: '725054805811',
    projectId: 'course-compass',
    storageBucket: 'course-compass.appspot.com',
    iosClientId:
        '725054805811-9cna5llrcja6184d5rim1g67boa4eq7s.apps.googleusercontent.com',
    iosBundleId: 'com.example.courseCompass.RunnerTests',
  );
}
